version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      next:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"
      react:
        patterns:
          - "react"
          - "react-*"
          - "@types/react"
          - "@types/react-*"
      three:
        patterns:
          - "three"
          - "@types/three"
          - "@react-three/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "actions/*"
